# Generated by Django 5.1.2 on 2025-04-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0002_topic_alter_comment_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Published date'),
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published'), ('AR', 'Archived')], default='DF', max_length=2, verbose_name='Status'),
        ),
    ]
