# Generated by Django 5.1.2 on 2025-05-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniblog', '0003_post_published_date_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='nickname'),
        ),
    ]
